package com.example.gitsearchapl.room

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "star_repository_table")
data class StarRepository(
    @PrimaryKey(autoGenerate = true)
    val id: Int,
    val name_repository: String,
    val html_url: String,
    val star: Int
)
/*"html_url": "https://github.com/marcj/css-element-queries",
      "description": "CSS Element-Queries aka Container Queries. High-speed element dimension/media queries in valid css.",
      "fork": false,
      "url": "https://api.github.com/repos/marcj/css-element-queries",
      "forks_url": "https://api.github.com/repos/marcj/css-element-queries/forks",
      "keys_url": "https://api.github.com/repos/marcj/css-element-queries/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/marcj/css-element-queries/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/marcj/css-element-queries/teams",
      "hooks_url": "https://api.github.com/repos/marcj/css-element-queries/hooks",
      "issue_events_url": "https://api.github.com/repos/marcj/css-element-queries/issues/events{/number}",
      "events_url": "https://api.github.com/repos/marcj/css-element-queries/events",
      "assignees_url": "https://api.github.com/repos/marcj/css-element-queries/assignees{/user}",
      "branches_url": "https://api.github.com/repos/marcj/css-element-queries/branches{/branch}",
      "tags_url": "https://api.github.com/repos/marcj/css-element-queries/tags",
      "blobs_url": "https://api.github.com/repos/marcj/css-element-queries/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/marcj/css-element-queries/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/marcj/css-element-queries/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/marcj/css-element-queries/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/marcj/css-element-queries/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/marcj/css-element-queries/languages",
      "stargazers_url": "https://api.github.com/repos/marcj/css-element-queries/stargazers",
      "contributors_url": "https://api.github.com/repos/marcj/css-element-queries/contributors",
      "subscribers_url": "https://api.github.com/repos/marcj/css-element-queries/subscribers",
      "subscription_url": "https://api.github.com/repos/marcj/css-element-queries/subscription",
      "commits_url": "https://api.github.com/repos/marcj/css-element-queries/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/marcj/css-element-queries/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/marcj/css-element-queries/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/marcj/css-element-queries/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/marcj/css-element-queries/contents/{+path}",
      "compare_url": "https://api.github.com/repos/marcj/css-element-queries/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/marcj/css-element-queries/merges",
      "archive_url": "https://api.github.com/repos/marcj/css-element-queries/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/marcj/css-element-queries/downloads",
      "issues_url": "https://api.github.com/repos/marcj/css-element-queries/issues{/number}",
      "pulls_url": "https://api.github.com/repos/marcj/css-element-queries/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/marcj/css-element-queries/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/marcj/css-element-queries/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/marcj/css-element-queries/labels{/name}",
      "releases_url": "https://api.github.com/repos/marcj/css-element-queries/releases{/id}",
      "deployments_url": "https://api.github.com/repos/marcj/css-element-queries/deployments",
      "created_at": "2013-06-01T17:48:50Z",
      "updated_at": "2021-12-25T07:50:14Z",
      "pushed_at": "2021-07-09T19:18:58Z",
      "git_url": "git://github.com/marcj/css-element-queries.git",
      "ssh_url": "git@github.com:marcj/css-element-queries.git",
      "clone_url": "https://github.com/marcj/css-element-queries.git",
      "svn_url": "https://github.com/marcj/css-element-queries",
      "homepage": "http://marcj.github.io/css-element-queries/",
      "size": 3089,
      "stargazers_count": 4214,
      "watchers_count": 4214,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": true,
      "forks_count": 510,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 55,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [
        "css",
        "element-query",
        "media-query",
        "responsive"
      ],
      "visibility": "public",
      "forks": 510,
      "open_issues": 55,
      "watchers": 4214,
      "default_branch": "master",
      "score": 1.0
    },*/